version: '3'
volumes:
  mysql-data:
    driver: local

  redis-data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: crudbooster-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret

  redis:
    image: redis:5.0-alpine
    command: 'redis-server --requirepass acme'
    container_name: crudbooster-redis
    command: --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  php:
    image: ambientum/php:7.3-nginx
    container_name: crudbooster-php
    volumes:
      - ./app/:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - redis